### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by mspaulding06** [maitria/avi#19]
I attempted to build the project using `lein run` and it failed with the following error.

```
Exception in thread "main" java.lang.IllegalArgumentException: No matching method: isAlphabetic, compiling:(avi/edit_context/operate/word.clj:12:12)
```

Using the following:
lein 2.6.1
clojure 1.8.0
MacOSX 10.11.5

**Comment by onealexharms** [comment]
What Java version?

**Comment by mspaulding06** [comment]
Java 1.6.0_65 ... that's probably the problem, isn't it?

**Comment by onealexharms** [comment]
It looks like it might be. We might not be able to look at it for a few days, but that seems very likely. (Sorry for the delay. We're lowkey moving.)

**Comment by mspaulding06** [comment]
Checking the Java documentation it looks like the `isAlphabetic` function wasn't supported until Java 7, so that explains my error.

https://docs.oracle.com/javase/7/docs/api/java/lang/Character.html#isAlphabetic(int)
