### ISSUE TITLE
"Permission denied" on Ubuntu 13.10 

### ISSUE THREAD

**Issue by micrub** [maitria/avi#6]
Getting permission denied.
Should I run "lein install" as root by design ?
...
e008212|master✓
lein install  
                                                                                                                                                                                   
Compiling 1 source files to /home/michael/projects/github/avi/target/classes
Compiling avi.install
Created /home/michael/projects/github/avi/target/avi-0.1.1.jar
Created /home/michael/projects/github/avi/target/avi-0.1.1-standalone.jar
install: cannot change permissions of ‘/usr/local/share/avi/’: No such file or directory

install: cannot create regular file ‘/usr/local/bin/avi’: Permission denied

install: cannot create regular file ‘/usr/local/share/avi//avi.jar’: No such file or directory

/usr/bin/ld: cannot open output file /usr/local/lib/libavi_jni.so: Permission denied
collect2: error: ld returned 1 exit status
...

**Comment by justgage** [comment]
I find it's rather problematic to run it as root because it means that any files created during that install process are the root's files meaning you basically have to run lein as sudo every time.

**Comment by eraserhd** [comment]
I think the best way to do this is to add a `:prefix` option, so it could be installed like so:

```
$ lein install :prefix ~/bin
```

What do you think?

**Comment by justgage** [comment]
I think that would be a good solution! The ability for someone to specify where it goes could be really good.
